// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativehidecontents.proxies;

public class NativeAppContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestNativeHideContents.NativeAppContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContextState("ContextState"),
		TestDate("TestDate"),
		WriteToLog("WriteToLog");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject)
	{
		if (nativeAppContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nativeAppContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nativeAppContextMendixObject = nativeAppContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testnativehidecontents.proxies.NativeAppContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testnativehidecontents.proxies.NativeAppContext(context, mendixObject);
	}

	public static testnativehidecontents.proxies.NativeAppContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testnativehidecontents.proxies.NativeAppContext.initialize(context, mendixObject);
	}

	/**
	 * Get value of ContextState
	 * @param contextstate
	 */
	public final testnativehidecontents.proxies.ContextState getContextState()
	{
		return getContextState(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextState
	 */
	public final testnativehidecontents.proxies.ContextState getContextState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ContextState.toString());
		if (obj == null) {
			return null;
		}
		return testnativehidecontents.proxies.ContextState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ContextState
	 * @param contextstate
	 */
	public final void setContextState(testnativehidecontents.proxies.ContextState contextstate)
	{
		setContextState(getContext(), contextstate);
	}

	/**
	 * Set value of ContextState
	 * @param context
	 * @param contextstate
	 */
	public final void setContextState(com.mendix.systemwideinterfaces.core.IContext context, testnativehidecontents.proxies.ContextState contextstate)
	{
		if (contextstate != null) {
			getMendixObject().setValue(context, MemberNames.ContextState.toString(), contextstate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ContextState.toString(), null);
		}
	}

	/**
	 * @return value of TestDate
	 */
	public final java.util.Date getTestDate()
	{
		return getTestDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TestDate
	 */
	public final java.util.Date getTestDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TestDate.toString());
	}

	/**
	 * Set value of TestDate
	 * @param testdate
	 */
	public final void setTestDate(java.util.Date testdate)
	{
		setTestDate(getContext(), testdate);
	}

	/**
	 * Set value of TestDate
	 * @param context
	 * @param testdate
	 */
	public final void setTestDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date testdate)
	{
		getMendixObject().setValue(context, MemberNames.TestDate.toString(), testdate);
	}

	/**
	 * @return value of WriteToLog
	 */
	public final java.lang.Boolean getWriteToLog()
	{
		return getWriteToLog(getContext());
	}

	/**
	 * @param context
	 * @return value of WriteToLog
	 */
	public final java.lang.Boolean getWriteToLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WriteToLog.toString());
	}

	/**
	 * Set value of WriteToLog
	 * @param writetolog
	 */
	public final void setWriteToLog(java.lang.Boolean writetolog)
	{
		setWriteToLog(getContext(), writetolog);
	}

	/**
	 * Set value of WriteToLog
	 * @param context
	 * @param writetolog
	 */
	public final void setWriteToLog(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean writetolog)
	{
		getMendixObject().setValue(context, MemberNames.WriteToLog.toString(), writetolog);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nativeAppContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testnativehidecontents.proxies.NativeAppContext that = (testnativehidecontents.proxies.NativeAppContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
