// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("e2cb02e4-dfb2-41af-ace7-7c1a5a569c9f"),
	Geocodio("a3ac5f40-0e58-471e-8705-4f0e660d473d"),
	LocationIQ("85f8cc1f-15a2-4bda-a222-66343a1d229d"),
	MapQuest("001650de-45f1-4361-a790-fc65cf71ba35");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
