// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("ed6557f0-bd1f-45a9-95cc-05d536419d35"),
	Geocodio("da1b3fbe-713c-42ed-8050-2e9ae9bc294c"),
	LocationIQ("323f1d8d-0300-4e40-8e63-7c46b673efa5"),
	MapQuest("161e9d2b-bb10-43e3-938b-006de5cae7e3");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
