// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("735b78d0-f7b0-44da-be5c-76d87af5c082"),
	startsWith("47c50926-f7bd-4daa-be4c-42f75fbfa90d"),
	endsWith("93c471e7-f9bc-495d-9f61-f49245afff29"),
	between("ae5242b1-f6ed-4078-8f95-6278155e24b1"),
	greater("d0b15149-b509-4256-abf4-489dac823765"),
	greaterEqual("5f72e7cb-67e9-46a2-98ad-bd70ae1e4a25"),
	equal("91ed7b37-16f7-49b7-ae95-955d1b065356"),
	notEqual("232ee400-30f7-4c10-8d48-986e00c2dc98"),
	smaller("a30a811d-b772-4a2e-b09e-908237b50dc9"),
	smallerEqual("cb0f8a71-86fb-443f-aec2-b063589d75af"),
	empty("15235348-1774-46e2-ba76-af1b7866b9d3"),
	notEmpty("e8b33aec-e24a-4ae6-a34f-52e7ae942472");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
