// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("a7814859-35cc-4404-a61b-e8dfc21db22e"),
	startsWith("0ca9850d-cd7e-4d09-834b-68100d2266b2"),
	endsWith("cf0986d3-eb40-4086-9380-bf86fcc20d6a"),
	between("56b70cc5-9bb4-43bc-9512-7c5f55c92cd1"),
	greater("3add41da-df04-4663-9c92-f71ef93b0c1d"),
	greaterEqual("b74ee30a-7f32-4576-8370-51260ea9763a"),
	equal("4cdb3539-7d3a-4da4-a446-2fade209f0b2"),
	notEqual("2e188332-a0b4-4158-bff4-50237cdf42ac"),
	smaller("cf9b31b2-be8f-4cdf-9c41-0e62c1d551b1"),
	smallerEqual("11646049-b99a-4c63-8b8a-3874579e7743"),
	empty("f58219e2-2190-4f22-87c2-8e47d9431957"),
	notEmpty("34d0e77e-ab08-434c-bddc-b5cc881a384e");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
