// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("c31b5238-526a-420d-995b-1afb15ebc430"),
	denied("fb4a3ae0-ab1e-483f-8bbc-940b6f4386eb"),
	limited("c6a4c83a-2aa6-43a5-8532-244756088de6"),
	granted("920f1b17-c6a4-4c41-83e4-4f790748dafc"),
	blocked("0d3241a8-83ed-42d9-8833-ec4ae10b2c29");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
