// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("2195dcb2-d1fc-479e-99ce-132981245f04"),
	denied("ca30799f-25dc-44ee-9058-1dc46f634a62"),
	limited("a07e557b-53f8-4859-890d-206f68c2a1a5"),
	granted("19198950-111a-4c0e-89e0-6bb55a025d1d"),
	blocked("da7492bd-3cfe-47e6-bf4b-2be55bf131b9");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
