// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("dd41d1b2-a380-4cad-877c-a1f00c19a578"),
	denied("75b96351-9576-4874-9ec1-05f92106fc8a"),
	limited("f9cf0055-5439-4379-8e93-e9506087c98b"),
	granted("b62eb2d2-1a86-4323-8682-5938b22d86af"),
	blocked("1d20ae02-abbf-4b7e-a730-777d3393a535");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
