// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum InAppBrowserDismissButtonStyle
{
	done("10273cc4-d5d1-461a-8dbb-f617488de194"),
	close("ffa79cc5-0791-4b17-a52d-ef7d17b61ee6"),
	cancel("e0963d31-d355-48dd-9f74-6613fb53c155");

	private final java.lang.String i18nCaptionKey;
	
	private InAppBrowserDismissButtonStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
