// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("83df63a0-b745-4977-820d-6fcf85f6dd08"),
	low("bb9ce6ca-ca58-4d29-9c5e-fe7a18064791"),
	medium("a9e5be55-38a1-4812-9598-3706a68768f5"),
	high("3d136f79-f06d-40a2-b7a7-a7aa0639c10f"),
	custom("9b5e4e4a-a802-4251-9bfb-63da5116595c");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
