// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("cd5ce9d3-bf35-44ef-b723-d511dddc9265"),
	low("b439fadd-4ec8-48af-8d78-cb322d0f1e04"),
	medium("61241336-39ad-4034-82fb-acce6cf829d3"),
	high("40c7654e-3e6d-40e8-a238-46a62b2fe70d"),
	custom("f54c16df-1965-434f-bc83-f85b4e06dba6");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
