// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarHideShowAnimation
{
	none("33e8e694-8069-4e5b-853a-75156807ea0e"),
	fade("c499bd44-7068-48c4-b125-10c21720199e"),
	slide("3b94c34b-06c2-4d3b-bdf3-11e7ce8e5afb");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarHideShowAnimation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
